### ISSUE TITLE
Some of the new routes don't work

### ISSUE THREAD

**Issue by KingSupernova31** [lunakv/academyruins-api#28]
Navigating to `https://api.academyruins.com/cr/keywords` returns `{"detail":"Rule not found","ruleNumber":"keywords"}`.

The same problem exists for the glossary and unofficial-glossary, though these can be fixed by adding a trailing slash. (That fix does not work for keywords).

**Comment by lunakv** [comment]
Whoopsie. Fixed.

**Comment by KingSupernova31** [comment]
While not a huge problem, I'll note that the routes are still oddly sensitive to the existence of a trailing slash. `/cr/keywords` works properly, but `/cr/keywords/` returns no response. Conversely, `/cr/` works properly, but `/cr` does not.

**Comment by lunakv** [comment]
"Returns no response" is not quite accurate. In these situations, the framework simply returns a 307 reditect to the canonical route. This may appear as no response when testing with something like `curl`, but for any client that's able to follow redirects, the only difference is the extra round trip.

I do plan to make the trailing slash completely irrelevant at some point just for simplicity, but I wouldn't classify the current behavior as an issue really.
