### ISSUE TITLE
AR doesn't properly split keywords that the CR combines into one section

### ISSUE THREAD

**Issue by KingSupernova31** [lunakv/academyruins-api#45]
https://api.academyruins.com/cr/keywords

Currently affects daybound/nightbound and tap/untap. AR thinks that the string "daybound and nightbound" is a single keyword.

Probably the best fix would be to split any keyword that contains the string " and ", though that runs the risk of breaking if Wizards ever releases a multi-word keyword that includes "and". Keywords are supposed to be short and elegant though, so I doubt they'll do that any time soon.

**Comment by KingSupernova31** [comment]
Is there an easy way to tell when changes like these have gone live, or were supposed to go live? I notice it's still not working on the live API, and I want to report that if it's a bug, but if the delay is intended and it's going to go live in the future I don't want to be a bother about it.

**Comment by lunakv** [comment]
All changes go live whenever a release is published. With this change in particular, the code that generates the keyword list is updated in production, but I didn't think to swap out the current keywords file with a new one. I'll try to do that, at the very latest this change will be in effect after a new CR release
