### ISSUE TITLE
Trace

### ISSUE THREAD

**Issue by lunakv** [lunakv/academyruins-api#9]
Given a rule number and a set, what is the full changelog history of the rule that was said number at said set? This would be an interesting question to answer.

The two pieces of data we need for this are rule diffs, which we already track, and rule renumberings, which the diff engine already emits, but which aren't stored anywhere yet.

**Comment by KingSupernova31** [comment]
Note that if the rule renumberings are calculated the same way VJ calculated them, it'll miss some that get renumbered at the same time they change slightly. (And it can also get some false positives when a rule changes so much that the engine thinks its a different rule.) In order for this to be highly reliable, I think it'd be best to have a hybrid system where the diffs are generated automatically, then a human fixes any errors, and that final version after the human's corrections is stored as the canonical diff.

**Comment by lunakv** [comment]
They are not. The diff engine was rewritten almost completely from scratch, in part to address the missing rules. The problem of a rule changing so much it's not recognized as the same rule is of course still there, and seems basically unsolvable. The hybrid system you're proposing is exactly how diffs are currently generated.
